--直接Unityには登録しないスクリプト。いわゆる、ライブラリ化した奴

-- プレイヤーキャラクター定義
PlayerCharacterConfig = {
	{
		IdIndex = 1,
		PrefabName = "Prefabs/PlayerCharacterObject001",
		Name = "PlayerCharacterObject001",
		Width = 128,
		Height = 128,
		NowHp = 100,
		MaxHp = 100,
		DetailText = "名前はもち\n白くてもちもちしている。かわいい。\n\n攻撃方法は連射速度の速い直線の弾を撃つ。",
		SkillConfig = SkillData.new(SkillTable_001),
		SkillDetailText = SkillDetailText001,
		UnlockNeedValue = 0,
		HomePlayerPrefabName = "Prefabs/HomeCharacter1",
		HomePlayerName = "HomeCharacter1",
		BaseParameter = CharacterParameter.new(100, 1, 1, 0),
		AddParameter = CharacterParameter.new(0, 0, 0, 0),
		GrowType = {
			Hp = 3,
			Attack = 3,
			Deffense = 3,
		},
	},
	{
		IdIndex = 2,
		PrefabName = "Prefabs/PlayerCharacterObject002",
		Name = "PlayerCharacterObject002",
		Width = 128,
		Height = 128,
		NowHp = 50,
		MaxHp = 100,
		DetailText = "名前はとら\nおでこの縦しまが3本。イノシシではない。かわいい。\n\n攻撃方法は貫通力のある直線の弾を撃つ。",
		SkillConfig = SkillData.new(SkillTable_001),
		SkillDetailText = SkillDetailText001,
		UnlockNeedValue = 0,
		HomePlayerPrefabName = "Prefabs/HomeCharacter2",
		HomePlayerName = "HomeCharacter2",
		BaseParameter = CharacterParameter.new(100, 2, 2, 0),
		AddParameter = CharacterParameter.new(0, 0, 0, 0),
		GrowType = {
			Hp = 4,
			Attack = 4,
			Deffense = 1,
		},
	},
	{
		IdIndex = 3,
		PrefabName = "Prefabs/PlayerCharacterObject003",
		Name = "PlayerCharacterObject003",
		Width = 128,
		Height = 128,
		NowHp = 50,
		MaxHp = 100,
		DetailText = "名前はぶち\nところどころぶち。かわいい。\n\n攻撃方法は変則的に曲がる弾を撃つ。",
		SkillConfig = SkillData.new(SkillTable_001),
		SkillDetailText = SkillDetailText001,
		UnlockNeedValue = 500,
		HomePlayerPrefabName = "Prefabs/HomeCharacter3",
		HomePlayerName = "HomeCharacter3",
		BaseParameter = CharacterParameter.new(100, 3, 3, 0),
		AddParameter = CharacterParameter.new(0, 0, 0, 0),
		GrowType = {
			Hp = 2,
			Attack = 2,
			Deffense = 5,
		},
	},
	{
		IdIndex = 4,
		PrefabName = "Prefabs/PlayerCharacterObject004",
		Name = "PlayerCharacterObject004",
		Width = 128,
		Height = 128,
		NowHp = 50,
		MaxHp = 100,
		DetailText = "名前はさくら\nほっぺがチャームポイント。かわいい。\n\n攻撃方法は未定。",
		SkillConfig = SkillData.new(SkillTable_001),
		SkillDetailText = SkillDetailText001,
		--UnlockNeedValue = 500,
		UnlockNeedValue = 0,
		HomePlayerPrefabName = "Prefabs/HomeCharacter4",
		HomePlayerName = "HomeCharacter4",
		BaseParameter = CharacterParameter.new(100, 4, 4, 0),
		AddParameter = CharacterParameter.new(0, 0, 0, 0),
		GrowType = {
			Hp = 3,
			Attack = 3,
			Deffense = 3,
		},
	},
}


